### ISSUE TITLE
支持英文审核吗

### ISSUE THREAD

**Issue by user-zzw** [LL4J/Filter4J#1]
我看里面的词库都是中文的，之后可以支持英文吗

**Comment by huzpsb** [comment]
暂时没有此类计划。
不过，您可以选择改用：
https://github.com/siuank/ADDetector4J
或
移步Filter4Jx自行训练~

**Comment by itcrazy0918** [comment]
请问Train_4.java训练代码中缺失的 ts.model、train.csv等文件能共享一下吗？

**Comment by huzpsb** [comment]
> 请问Train_4.java训练代码中缺失的 ts.model、train.csv等文件能共享一下吗？

https://github.com/LL4J/Filter4Jx/issues/1
